@baseUrl = http://localhost:4000/api
@resourceName = todolist
# Categories

# @name getAll
GET {{baseUrl}}/{{resourceName}}

#####

# @name filter
GET {{baseUrl}}/{{resourceName}}?email=kienlol@gmail.com&
#####

# @name paginate
GET {{baseUrl}}/{{resourceName}}?_page=3&_limit=10

#####

# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=name&_order=desc

#####

# @name add
POST {{baseUrl}}/{{resourceName}}/data
Content-Type:  application/json

{
    "Place": "Bà Nà Hill",
    "Note": "ffsfsfsfsfsfsfsf",
    "status": true   
}   

#####

# @name update
PUT {{baseUrl}}/{{resourceName}}/53
Content-Type:  application/json
{
    "id":53,
    "like": 13
}

#####

# @name remove
DELETE {{baseUrl}}/{{resourceName}}/53